set_property PACKAGE_PIN D18 [get_ports i_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports i_uart_rx]
set_property PACKAGE_PIN D17 [get_ports o_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports o_uart_tx]

# J7 pin 1 / DEBUG_1.  The externally-powered DS18B20 module provides its own
# 10 kohm pull-up to J7 pin 20 (+3.3 V), so no internal pull-up is enabled.
set_property PACKAGE_PIN G17 [get_ports ds18b20_dq_io]
set_property IOSTANDARD LVCMOS33 [get_ports ds18b20_dq_io]
set_property DRIVE 4 [get_ports ds18b20_dq_io]
set_property SLEW SLOW [get_ports ds18b20_dq_io]

set_property PACKAGE_PIN AD12 [get_ports { i_sys_clk_p }]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports { i_sys_clk_p }]
set_property PACKAGE_PIN AD11 [get_ports { i_sys_clk_n }]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports { i_sys_clk_n }]

# UART RX is asynchronous to clk_soc.  Cut only the external-port path into
# the ASYNC_REG synchronizer; the synchronizer's internal stage-to-stage path
# remains timed.  UART TX and the debug displays have no synchronous external
# sampling clock on the contest board, so their output paths are explicitly
# declared asynchronous board interfaces.
set_false_path -from [get_ports i_uart_rx] \
  -to [get_pins {u_soc/u_peripherals/u_uart/rx_sync_q_reg[0]/D}]
set_false_path -to [get_ports o_uart_tx]
set_false_path -to [get_ports {virtual_led[*]}]
set_false_path -to [get_ports {virtual_seg[*]}]
# The 1-Wire slave response is asynchronous at the pad.  Only the path into
# the first ASYNC_REG stage is cut; the synchronizer and all 50 MHz island
# logic remain timed.  DQ output-enable timing is protocol based, not source
# synchronous to an external clock.
set_false_path -from [get_ports ds18b20_dq_io] \
  -to [get_pins {u_temperature_island/u_sensor/dq_sync_q_reg[0]/D}]
set_false_path -to [get_ports ds18b20_dq_io]
set_property PACKAGE_PIN B27 [get_ports { virtual_led[31] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[31] }]
set_property PACKAGE_PIN A27 [get_ports { virtual_led[30] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[30] }]
set_property PACKAGE_PIN A26 [get_ports { virtual_led[29] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[29] }]
set_property PACKAGE_PIN B25 [get_ports { virtual_led[28] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[28] }]
set_property PACKAGE_PIN A25 [get_ports { virtual_led[27] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[27] }]
set_property PACKAGE_PIN B24 [get_ports { virtual_led[26] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[26] }]
set_property PACKAGE_PIN B23 [get_ports { virtual_led[25] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[25] }]
set_property PACKAGE_PIN A23 [get_ports { virtual_led[24] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[24] }]
set_property PACKAGE_PIN E30 [get_ports { virtual_led[23] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[23] }]
set_property PACKAGE_PIN C30 [get_ports { virtual_led[22] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[22] }]
set_property PACKAGE_PIN D28 [get_ports { virtual_led[21] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[21] }]
set_property PACKAGE_PIN E26 [get_ports { virtual_led[20] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[20] }]
set_property PACKAGE_PIN F25 [get_ports { virtual_led[19] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[19] }]
set_property PACKAGE_PIN D23 [get_ports { virtual_led[18] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[18] }]
set_property PACKAGE_PIN F23 [get_ports { virtual_led[17] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[17] }]
set_property PACKAGE_PIN F12 [get_ports { virtual_led[16] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[16] }]
set_property PACKAGE_PIN G28 [get_ports { virtual_led[15] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[15] }]
set_property PACKAGE_PIN E28 [get_ports { virtual_led[14] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[14] }]
set_property PACKAGE_PIN C29 [get_ports { virtual_led[13] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[13] }]
set_property PACKAGE_PIN D26 [get_ports { virtual_led[12] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[12] }]
set_property PACKAGE_PIN C25 [get_ports { virtual_led[11] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[11] }]
set_property PACKAGE_PIN D24 [get_ports { virtual_led[10] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[10] }]
set_property PACKAGE_PIN E23 [get_ports { virtual_led[9] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[9] }]
set_property PACKAGE_PIN G23 [get_ports { virtual_led[8] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[8] }]
set_property PACKAGE_PIN E29 [get_ports { virtual_led[7] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[7] }]
set_property PACKAGE_PIN G25 [get_ports { virtual_led[6] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[6] }]
set_property PACKAGE_PIN F26 [get_ports { virtual_led[5] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[5] }]
set_property PACKAGE_PIN C26 [get_ports { virtual_led[4] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[4] }]
set_property PACKAGE_PIN E25 [get_ports { virtual_led[3] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[3] }]
set_property PACKAGE_PIN C24 [get_ports { virtual_led[2] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[2] }]
set_property PACKAGE_PIN E24 [get_ports { virtual_led[1] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[1] }]
set_property PACKAGE_PIN G24 [get_ports { virtual_led[0] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_led[0] }]
set_property PACKAGE_PIN L16 [get_ports { virtual_seg[9] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[9] }]
set_property PACKAGE_PIN L13 [get_ports { virtual_seg[8] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[8] }]
set_property PACKAGE_PIN K13 [get_ports { virtual_seg[7] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[7] }]
set_property PACKAGE_PIN L12 [get_ports { virtual_seg[6] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[6] }]
set_property PACKAGE_PIN K15 [get_ports { virtual_seg[5] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[5] }]
set_property PACKAGE_PIN K16 [get_ports { virtual_seg[4] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[4] }]
set_property PACKAGE_PIN J16 [get_ports { virtual_seg[3] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[3] }]
set_property PACKAGE_PIN H16 [get_ports { virtual_seg[2] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[2] }]
set_property PACKAGE_PIN L15 [get_ports { virtual_seg[1] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[1] }]
set_property PACKAGE_PIN K14 [get_ports { virtual_seg[0] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[0] }]
set_property PACKAGE_PIN K11 [get_ports { virtual_seg[19] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[19] }]
set_property PACKAGE_PIN J14 [get_ports { virtual_seg[18] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[18] }]
set_property PACKAGE_PIN G13 [get_ports { virtual_seg[17] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[17] }]
set_property PACKAGE_PIN F13 [get_ports { virtual_seg[16] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[16] }]
set_property PACKAGE_PIN H12 [get_ports { virtual_seg[15] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[15] }]
set_property PACKAGE_PIN J11 [get_ports { virtual_seg[14] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[14] }]
set_property PACKAGE_PIN L11 [get_ports { virtual_seg[13] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[13] }]
set_property PACKAGE_PIN J12 [get_ports { virtual_seg[12] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[12] }]
set_property PACKAGE_PIN H11 [get_ports { virtual_seg[11] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[11] }]
set_property PACKAGE_PIN J13 [get_ports { virtual_seg[10] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[10] }]
set_property PACKAGE_PIN AH26 [get_ports { virtual_seg[29] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[29] }]
set_property PACKAGE_PIN AF28 [get_ports { virtual_seg[28] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[28] }]
set_property PACKAGE_PIN AF30 [get_ports { virtual_seg[27] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[27] }]
set_property PACKAGE_PIN AJ26 [get_ports { virtual_seg[26] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[26] }]
set_property PACKAGE_PIN AH27 [get_ports { virtual_seg[25] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[25] }]
set_property PACKAGE_PIN AF26 [get_ports { virtual_seg[24] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[24] }]
set_property PACKAGE_PIN AC26 [get_ports { virtual_seg[23] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[23] }]
set_property PACKAGE_PIN AF27 [get_ports { virtual_seg[22] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[22] }]
set_property PACKAGE_PIN AG27 [get_ports { virtual_seg[21] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[21] }]
set_property PACKAGE_PIN AG28 [get_ports { virtual_seg[20] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[20] }]
set_property PACKAGE_PIN AJ28 [get_ports { virtual_seg[39] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[39] }]
set_property PACKAGE_PIN AH30 [get_ports { virtual_seg[38] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[38] }]
set_property PACKAGE_PIN AK29 [get_ports { virtual_seg[37] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[37] }]
set_property PACKAGE_PIN AK28 [get_ports { virtual_seg[36] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[36] }]
set_property PACKAGE_PIN AK30 [get_ports { virtual_seg[35] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[35] }]
set_property PACKAGE_PIN AG30 [get_ports { virtual_seg[34] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[34] }]
set_property PACKAGE_PIN AE30 [get_ports { virtual_seg[33] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[33] }]
set_property PACKAGE_PIN AJ27 [get_ports { virtual_seg[32] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[32] }]
set_property PACKAGE_PIN AJ29 [get_ports { virtual_seg[31] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[31] }]
set_property PACKAGE_PIN AK26 [get_ports { virtual_seg[30] }]
set_property IOSTANDARD LVCMOS18 [get_ports { virtual_seg[30] }]

# Board schematic xc7k325t-V2.1 page 2 ties the Kintex-7 CFGBVS_0 pin to
# VCC3V3, and the configuration flash is powered from the same VCC3V3 rail.
# State those board electrical facts explicitly so Vivado can validate bank 0.
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
